[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "https://cheffhub.netlify.app"
    access-control-allow-methods = "GET"
    access-control-allow-headers = "*"

[functions]
  external_node_modules = ["express", "axios"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/recipes/*"
  to = "/.netlify/functions/recipes/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/news/*"
  to = "/.netlify/functions/news/:splat"
  force = true
  status = 200